/* mkstnds.c: Read scortabl.asc and make a table of standards
	in each age-group and event. The file produced is called
	table.c and is included in my score project.
*/

/* THIS FILE MUST BE COMPILED AND LINKED WITH atosecs.c */

/* Procedure for adding a new age group.
1. Add the new age group standards at the appropriate place in 
   scortabl.asc.
2. Add 1 to the NOAGEGROUPS #define below
3. Add the name of the new age group at the appropriate place in
   the char *AgeGroups[] array in runner.cc
4. Do make mkstnds to create a new mkstnds program.
5. Run mkstnds to create a new table.c
6. Modify the int AgeGroupNo routine in runner.cc to calculate the
   appropriate age group index.
7. Make score.
*/

/* NB. This file assumes that the standards for each agegroup are
in a file in this directory called scortabl.asc. It is a plain ascii file.
Each line in the file has the following format:

M39 200m ;time1; ...

WARNING: DON'T LEAVE OUT THE SECOND SEMICOLON!

The first semicolon is in column 10. The times are given in hh:mm:sec.s
format. All times after the first one are irrelevant. The first time is
the "theoretical WR" produced by National Masters News.

This format is the same one used by Ed Stabler, because I got the 
standards file from him. If he changes it then this program obviously
must be rewritten.
*/

#include <stdlib.h>
#include <stdio.h>

#define NOEVENTS 15  /* Relays not included */
#define NOAGEGROUPS 32   /* Currently m11 - m84, f09-f69 */

#define HEADER "/* table.c: definition of the table of \
standards in each event and agegroup. \n\
DO NOT EDIT THIS FILE. It is created by mkstnds.\n\n */ "

extern double atosecs(char *);     /* time conversion program */

FILE *table;
FILE *output;

int
main()
{
	char buffer[256];
	char AgeGroup[4],Event[6],Time[15];
	char *ptr;
	int i;
	int row = 0,column = 0;

	AgeGroup[4] = '\0';       /* properly terminate strings */
	Event[6] = '\0';

/* Open input and output files */

	if((table = fopen("scortabl.asc","r"))==NULL){
		fprintf(stderr,"Unable to open scortabl.asc\n");
		exit(1);
	}
	if((output = fopen("table.c","w"))==NULL){
		fprintf(stderr,"Unable to open table.c\n");
		exit(1);
	}

/* Print top part of output file */

	fprintf(output,"%s\n",HEADER);
	fprintf(output,"double table[%d][%d];\n",NOAGEGROUPS
		,NOEVENTS);
	fprintf(output,"void InitTable(void){\n");

/* Read input file line by line and create each array entry in table */

	while(fgets(buffer,256,table)!=NULL){
		ptr = buffer;
		AgeGroup[0] = *ptr++;
		AgeGroup[1] = *ptr++;    /* e.g. M39 */
		AgeGroup[2] = *ptr++;
		ptr++;                /* skip whitespace */
		Event[0] = *ptr++;
		Event[1] = *ptr++;
		Event[2] = *ptr++;     /* e.g. 1500m */
		Event[3] = *ptr++;
		Event[4] = *ptr++;
		ptr++;                /* skip semicolon */
		i=0;
		while((Time[i++]=*ptr++)!=';');
		Time[--i]='\0';                   /* properly terminate */


		fprintf(output,"table[%d][%d] = %.2f;\n",
			row / NOEVENTS,column%NOEVENTS,atosecs(Time));
		row++;
		column++;
		}
		fprintf(output,"}\n");
/* clean up */
	fclose(output);
	fclose(table);
	return 0;
}
