# Convert TA records from Jack Graver's format to lines in our people.??? 
# file
# usage: gawk -f thisfile < path to ta data file
# NB: This is quick and dirty. You should edit the people file afterward
# to correct all the mistakes.
# The input file is the TA hiring data file produced by Graver's program
# with switches 1,1 set. Unfortunately, Graver's program will only print
# a file to PRN, so to capture the output in a file you will have to use
# one of the many programs available that fool DOS into thinking a file is
# the printer. 

BEGIN { print "\# The lines below have been generated by ta.awk from Jack Graver's data" }

/^[ 	]*[1-9]/ {split($2,name,"[,]");
	shortname = name[1]; 
	shortname = substr(shortname,1,1) tolower(substr(shortname,2));
	 firstname = name[2]; Citizenship = $4; Status = $5; Clearance =  $6;
	 Offer = $9;
# has the student declined offer ?
	 if( Offer == 3 || Offer == 4 ) next;
# guess type of appointment from status, citizenship, etc.
	if (Clearance != "C") 
		appttype = "TA3"
	else 
		if ( Status == "R")
			 appttype = "TA1"
	else
		if (Citizenship == 1 && Status == "N")
			 appttype = "TA2"
	else 
		if (Offer == 1) 
			appttype = "OFFER" 
	else
	appttype = "Unknown"
	longname = "\"" firstname " " shortname "\""
# Print out with sensible defaults
		print shortname, appttype, "NA","NA", 0, 0, 6, 18, longname 
 }
